#!/bin/bash
#SBATCH --job-name=IC50
#SBATCH --output=wjobs/job-IC50-%j.out
#SBATCH --error=wlogs/job-IC50-%j.log
#SBATCH --time=10-5:59:59
#SBATCH --mem-per-cpu=11G
#SBATCH --cpus-per-task=6
#SBATCH --array=1-99

source activate PGxG

INDEXFILE="./withinic50"

INDEX=$(awk "NR==$SLURM_ARRAY_TASK_ID" $INDEXFILE)
INDEX_ARR=(`echo ${INDEX}`)

DRUG=${INDEX_ARR[0]}
METRIC=${INDEX_ARR[1]}
METHOD=${INDEX_ARR[2]}

python ./Within.py --drug ${DRUG} --method ${METHOD} --metric ${METRIC} 